apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCWMgvss36i+MtD5t5020cV3TXKnu59MohcSm5adF0cjJJOuXOe1ui/cIpofD/HOK8cv2qLwGYsvFuNK3QOGWpcV0BdJDlgnE7m/s1IrEZ0iMPcGyGHHST+f1PwS8JY3juqvkHalF42OXHIXClMuYJf6/3qLItDM60irwyZD6YOHpOOV6/VQjCNpUVr4ARB9J83cjDfbR/e2WI3R5Lz7mH2bo9Qu4smH1yR7QQkdyxp0tW0WlfatPaMpQPQHt4wdojOsvu44VGzgPFcKTf/KsPTKnEWBsNp8kXDDvvtegglXTz3AlWgE/6mZf44ayQWyveOfOHtQYCDaYkRexE/kcPwcDWfh3RWNvZ98QD7bheNdd+Kx+BGfKijOV0/gIDro1ane2IeVZg38sbP/LYEj+bnQ6ypmyE9xUtjXTYlIioVSV5s99t5HiIWCjalglP3HUpP3/D/0WEnlBoZS5x3Rkc3XMkHMsLsC++bh/Fn1DhbomvUuQYzNszH1S1TZBJvFjTm/YalxLb4QHetctqgHnXLzYyckVp8rIyEwNwtCY9eLDSK4V7CgJXFUlJDKXNZbEV4MASUsO39nb0N7oFVB61SppBlfQNQ2yVO5KzW7V44v5QujsMY8kOVYt6/NAmR6EX5TFhklm1oIPGDMxyy/NajFS0PJzTVVvDGtNkCjPDvzuuwkQ897XS65qnyxgepUrpk1OK1VfUHpjRLkoBe5XaNLKIjF5MOJ003cfB1Led9zk3cznu8l7zqXFUNMffP7W7OrJUReVZHkOhT1K7odBUKAZV5elEeoLqfK609e7/sDg78EwRpmFt4d315czrlG03aT/j6htp1M0KW78eLshhetXR/qsr0BmxSBthNJIbLZju8oTMsbFkc+K+nTcgcNcysvYs/E7Y2vEGxyctxUF+MxiSUNxtUeMXxTGaMuRQfJxtL
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

