apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgDnCkTeWbD2cp3LMShMkSZ4wfJw1IroqJBiBaKHJZPtKNrMsb8RzZUIQFP3iPYb+EmfF/fQ8bcg/eWh4lTQ23tsxot+NA+lt6PRsjYcX/0QkPrxo0h27b+9gwoYPCaSWnhirk+89ra7LHpTsg4yUu3XmgemUCOOeyUZwfVihp8vF2jJqKhtBwGCYUyOj5cWw6IOYa/CiK4cImD1LkICcvw1NiHfMM1WBngwFr2BMneEMWoJvVTSH1rc46nX5ZO04WIa6bPB+0ExwSljUOyb32Ouawj5mLZ17Dl9YTV72MkG68P9r3un+7+TPR1RvCfdMKEBaIhG7L4Xltx7vasZh+1/WEduumlbm88saUDLn1kZAKg04pXGqL/mHS6JJzvXOXhV+JhKdDsVAhl+ToRIYC8pOFPzb2AM4BIw/1+b9ylfVhlkJcEdAikHpMadbu4hxHh8X1d2RY0oOPcaKlgOadq2P8aa1jLGZxiwUVJfySviHz6MBn7w+3ZWqjCY+7yAyUTv7arrd4pzxRV81H5s+WsOdjQs7/0FcNGZxCdeDu2V0MWT9WGkb9pTMD63CUbypBujDL8YrTsyHeIQFj9z5O9KsUtaV/wkPsYIw5OLQYCkbU4kYOKXrdAV8AnM4679hRbGOBGmSCrfBb8VQzHhXMZx9FUp7AiObEteIcDcDMaQZXr1RntVlh/R4z/ihq4GRg6cD6VjZyX/bWs+xlvS81A84QF6vbMM3Uv8MflenzwekE2y9o5OJjS8t5zgSsqfZKOmHnSWmlBHXVZhD0kxe83X4Y/kn85De8IXj/ihtvtVD9ZQ2NolpTitS5zOzzWLTdsuzLLm4ELnNY5UUcU9gzQSQpLyWH0rIWpfQ4GEUcwAKAdmRu+7IspGZJwuCYBjR9gG0Zv3gLGEOLEqjKHiesZl3naTi8raXWQzq5g+jTLVG/GB
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

