apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgATiPJl3ihJjQ5/tS2jAZdrpJyRHxsV5zgcr4EzcEvHL9FET/trsTNpJ2hbRsKEfCaMJVHZpyB0nC1cq8kCVSMfgkNF1htB4Mu28fBp+5++tgmKvt+hMKeSLHfSHvCSGtHy1n7xaS91KU7d+L/Qxhr+8T/BknZAu2CrgkIi1pZHh5pYNpTV/k9A98dMO1JZQRtJqq/8nhLtNQ0yJExljbwCOK6RU3qmZnTZKqgZFfaANE1w9a2r2tAcngHMPcUOFO3g0O4GBbA4VdCpG/SLhEIuPRHpGomwFfKLaT8tmqahgAiOSUqdTTUyUlbS1xgInJZ+yA3KB5dhEHn2uRWo8CTtOOyOxCBQgInQuQ857D4B7X8Lp5lXgFO20yMYfR8Q82+uyr7qK6PsETEMIYCAfqkmmz2qja+DilxX+YSRLgX9ra3NdRfyy9OknfPdCu7WZuDDuzZerS/nQTJRiO0S1MAWvO+Hamu5uWwKvBCrFjviMckc6PGTFEjSD+yLEEvu/CtXDirXhYsknwxWTrmjNMQ2pJ/VQfrkzbV9tLUsSYJODS3xfNC5lF9QijxO6RQ6IWZp01zUcuh1YMDfxRzxiyDa3lvCOEiRcPatjkHAae5Xq5LMXTvDfsG4XXXrHD48YQE6dBh+Tp+Ks0jdHDKftToMO3xCb2uNOd97atMJ28ZvCAoOym8VClfgnrWrbERTUk0TyVGq7PjLVpQ9v0JslGtemFEzwtl5PhR+GzQBEHExP+Xwq2wKQMh/JPplEgWGoeMyhxzw5lpeTf9sfOSq50i9gTGTCiIKWruD4LJygGK8/OHew0Dc70E4H4wWOzVsARFjf9p3C7eCIhLLZ1QyHln+fV3CiMfixOjvwc9/oDDkd7A33NzqefRl5eMtK51bl1LKAdweXij8eZCNaxT0ONfdj1DL4C73YUnWWvSP/sZYfHc8
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

