apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgClY3H2PDNreLS9TlR03a9tZyCSmqZlkE8EQmjD/YIKmBZPOFtMtcUZSXOPwsaEsDcq4D//JUt2pBCdIg8+7o2XJks7El2HCrpX+a9g7CgY7NxrsSYtnnwEBqXqDS9WdHmkqlz9XCvU4nsGgUJzqdvTT75iHhyYgU8fEQ0mfKWY5JHFI4DH6z9/NC336tl3jIdL1d7yI0XDHMI0KIn6k7w9BXwYrQwEFDkymkFWkk77kGuwPr/Aovba442EKYffJlvJQDktZC0Z9tbHQXX/x2Gfh3SM3SXmCtdd4O3P9MuJ+3aXrsknKEXgJq8/yvp3/WY+BJSmiKckQavpNvr7nWoKeTDK8VbZB3sjIBUy1tDsuT9Pp7hjSh8q18XnPnefE7jhpBMZ4+CVRd3JS5jyfepP77wyHSLmSIhn4yuFEJuk7JRphDWnbSJH7LBhGTJ5xOwk8tUZXIhOPYS85SPehfABkcsv5zvH4byyX0dzI+tdfBaNRPUsiZ/KLqeMbH7eUWopu+roU7f4koqJ5jJHCMWOa7t1HWCkZSdteYcei2nReXCv17+80t9QhrbtwrnMxCc/ZjFGYaE4Sod2tJCSLg4O3dWX1C/7K0ciZ4/EusaEDt77cScL/t+qL3B6bXfD2M/UIP0cnRIw54A1XoU3wuhzwSlteEe65qj6Bv2Xo+aDPc0D7h+qw5TVHvOUXAy8dc2w4xVQ1q9fOuGyZ3U6ix2DnazJdtz8VoKuF6IM2dDTfALTLiVAJC/WnSvgbKlu1rtJanPFeBp/LS5CtliBtvL2/kizIOWVHH78YE7+/+bbq5v3cUsRWSV4NMxgG/F1U8VTi/ylnKOGzGNJFYtZExk6TPvzR8kG5hrwtgsYGJ+K6Jb46mKy7JXkm+nLC8NQRo/lXAA8QhVH7a5vgAcv14dGxNtM7Oajz3lOTgpmHhk2VfSn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

