apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAfhUnWBU+FRaRqSL/DHePiw5guV8K4qIFGW00RsO5fsMbzOyFSjSXHZtfhf3ijPA74qipIyrjHU/+nRpJgP4WCdtSffOuphuodI6LhoN5LVDKE5H72luxQ9c25LgBnJvZ1h9zQ9p35tN9D7ZZ6GxTXkI40PW3fsnLjz+P539AIz3p7KsrWQki/tN9j+d0OWFbArQOijTfedgABmdbOSxojmEctTuI1hMZS9OlxQMUYtc+5BBwf3fw7hctZTm9lOMpPLVDTNMs7/soRh30zO3k1WrLNmHD5qyqUwoOU79fgv/xZ3E31p2zLPzsqYhrXjE64juXbxI2qoXS8RSI27R/gDHGtqrH9B5WdoZNZaVqj26XaknsOQq4goaawYmUQ9uoRTfJP7F455y4bXKPGL7n2bSrgQfohm7K89+4Hpo8IrJD/Zcjqym+dH5YsdR3eJKIPjHt6/iZLo2aqFmd7UvjxMVSWYgoN4UC+KG/jB/Cg6w1GOPDT/7z81fQxlgInfEQoU8qAa8HRRV2ykmMYOvuJdcrwugDDnzz4zYBpLs7+jwpQbxBSGMuZXVzP5uxuF92xK9bRXHBx4Rb5Hv4Pwu2b5V5DmtY+flwf3kDpjJXrZ82wYYi2J8z6Y+zc2C9d4J434FAEVnt+aa0TAkmV5xjlxgfvq9XYh8cHCmI1i2Py0g1RHPKB1EeD9dmHso91sgPohTOnQ8hrQ879QEtg6ZzAIh+VAEmYAojgdIBjMVXp5/v5KHjMFBfj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

