apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCZ5uReh+ZAcQEJ90zSqmvWBv8s3jxoyX7JFzOh8ou/tC472r+TD6spd3/aasLhFpvxX1cbvSqbkV6lgJ2y6ASRQ8NsCb3JVC3vCd+UCDm68lsG8F7SKI9Y19rEVTUEOoBwjQ6U/xn2J86amzWPqmZHrcgRWR3ekxkOk3Uke6P4U/it4vZx+rjGLzKdHPvaI2HC+iOsrXVBADUwQt7A+ASFYHcUk3cw3CRoy8nXzm85UwMPIhFyqm/6M6yI2U3yNzFDDbcRcsbLoPCQR6HonTwajxX7Gt2ycloiwC6xsCmGInlZohZc0Ita6Ew64cepGZnQNxw+7vvS2plc0hg0MsSJF2Kl80NGZMKfuZMbhO5ZkJ37/kuep3oOMQCFpHm5i7gs/7TRk5c9gYOickKZnahOS/mEGE3kPn9VMcLuxtlGX4Ys4L4D35DMvEnCdRpQY7E06r9gOAs8V/jfwQ3BWUuFqTdjGSbYsXSSPCwQ4g1oyt17kzOFx0I4knPF0wcZU9xa9KvdlR6drfwGi9LMVJzg6sAy+mf6yy3w8DRzUS48qAmNUGWD9N2+86CpXjJs/dW1y1Cdec+RpjVlSSo75tViKeKZDdw1nVUoVdKTlWBPqSrLcZBBBv7wdis0uo/8CwpbLiz8SDNbDhF9U1xvP7AlB5N9kngHa/aL4xcSTqNBuCfKjtr3cJP+1q51J6Z4Pjn36G5WoYVt0UDfaxxKpaBf3aHBOz4KMGHmBXaQJd2I8eaFP/oPnoos
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

