apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCHMm/764e+uXc8mdTkzOpJnDuvIDMaVXprG1tgUQ5LF6C/6oVDdbMDMDEuEAaoaA+E0fd9cxghcSszD6wFyTBAcasKFz7aFoKnDlcqOFtKsBq5ucb7+hC9LnRRktBq1r8LdboVLWRngGu2zOR1IIJbY7geLqOj2IpDSiYxtFkbC1A8/SmfGUPG/FEPhDb/7/HqcIFkjdJX5kpe59/k1COqh1vhoVHEbk7oOaPyHU7HA8rsSJjvoX8r63bgdjyp9GFwzYx6xvQXgHfFRNPYYrYBnr+il7fqVUiqEkCW59x3iu3n8+14ReDo3KTerA2HNjNFR2LvBft3T/qO//fAi8Op3dDEpGNPfEw16ByvDlL2HVmgOWeuizAQ/spbpCBbuFQQzwTAd2svo8N6YJ38/WhGVmzgrMGl9zEzF6EOK9KMX34fUbFM/8+W0ERH/TlXcJ8zA8jYOLqFTrTH9h44IuJuvbnZgWhLBOBXSDF1bRa58q9Li6arY0VrL/fqvvqQlF+JU1Z7tyLYIvFpfJUBQ6Fhax9Fm6yu1xJ+r9cy7nhicZKCCzkRBsAw/rzmksUQ8cCPQeTT4DA9lKFXhQFmPMFW4ly4gzl1yJ/HbJp088Ssfq+vFK27hJUpKNLzeWgYxvkpcVtJYeV/esybbvFCQO4D25PfubcR5Zb+vj26UcRkuJJLCCbkqDKh9IGR1OYrEpWw9v5mHouGbmI0x/Hdz6rqG1CxV5BHKdINCpJJcXN3cTM4WkpwqBf+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

