apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgC69gKhYbebPBnHNo1cLibhyW7kpFHTTRJQMZzCbyYulg7cna4uFMVc4CEu5e+I6RFHrpcBtjKs8xYEgBUyQYfqm/yLKaabJ9TzGmuYK2RIqvDE8Vmjs+gHAxOMqF6C5RVs9WCadonlq9NSwiFYAq6S1lay83cGIHD5sU5LGiRqXdOQlsw/Lmdvj71pkMi4dvrOfA6uTehJhF75Z0C7a2480oRclmTDpkAYpaHV5bvZZyICi266r2RxR097hGgbn1MKtpct0ydcCcnVSP0KbjKLy4s88v5kI07KwyyKNlNZk1yIoJdanhci6oL+/zMoML5tk59kW2+9c9mENygbY6SQtmpngczGiM4ywuYYXAWN/j7HRNWVO0nwUn7EiMGDtTFjQlfQa0lvU38CIZmDz4/hWe5g0zQaiZ/ywFgFxxsGLUm/FkOabIcTaB/RMwwbERh7L2y7JcswQFM4ZL+RN4a8BOHlat6LiL7G3DtOH4RW/e4UsgKn02+UhBe6YOxUw8CGe9K3PXsW5bSvFRsixhbBxgKvSuSajKNzktWWMoJHaOzAYQA/7AKpRTnmDHy7AshfAdNz9u5z9O9+PrfI2tQ3RVUsiIWN3FXYkb2tuFStlCaLzhJ5FTu6rkdhcpSNtujNx7omv04WdIRGxmWtE4Tbjy1Nxtthp2ldvsBaUTEWD7DETbl87FvsN8w2/prb9VDYZS0rjz7nEyWKFFw9bk6ruhxhauysBn1XfobkWHDwlDC+ife48bbR
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

